version: '3.9'

services:
  redis:
    image: redis:7-alpine
    networks:
    - quiz-backend-test-network

  db:
    image: postgres:15-alpine
    environment:
    - POSTGRES_USER=salmon
    - POSTGRES_PASSWORD=2810
    - POSTGRES_DB=dev_db
    - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - "5432:5432"
    networks:
    - quiz-backend-test-network

networks:
  quiz-backend-test-network:
    name: quiz-backend-test-network
    driver: bridge
